version: "3.8"
services:
  dynamodb-local:
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ".data/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal
  postgres:
    image: "postgres:14"
    container_name: postgres
    restart: "always"
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - "5432:5432"
    volumes:
      - ".data/postgres:/var/lib/postgresql/data"
  mongo:
    image: "mongo"
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_PASSWORD}"
    volumes:
      - ".data/mongo:/data/db"
  mongo-express:
    image: "mongo-express"
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"
    depends_on:
      - "mongo"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: "${MONGO_USERNAME}"
      ME_CONFIG_MONGODB_ADMINPASSWORD: "${MONGO_PASSWORD}"
      ME_CONFIG_MONGODB_URL: "mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongo:27017/"
  redis:
    image: "redis"
    container_name: redis
    restart: "always"
    ports:
      - "6379:6379"
    volumes:
      - ".data/redis:/data"
  minio:
    image: "minio/minio"
    container_name: minio
    restart: "always"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ".data/minio:/data"
    environment:
      MINIO_ROOT_USER: "${MINIO_ROOT_USER}"
      MINIO_ROOT_PASSWORD: "${MINIO_ROOT_PASSWORD}"
    command: server --console-address ":9001" /data
